### PR TITLE
[WIP]doc translation: biz-icon

### PR DESCRIPTION
**Pull request by xueqingxiao**

### CODE REVIEW

**Comment by xueqingxiao** [comment]
Any suggestion for translating this part? Because I think that [iconfont.cn](http://iconfont.cn/) is not best option for developer who is using english.

**Comment by nikogu** [comment]
iconfont.cn can change language to english.

image

**Comment by xueqingxiao** [comment]
@nikogu That's great. should I retake screenshot for this part, or you guys do this and upload to alipay CDN?

**Comment by chenshuai2144** [comment]
Already new, thank you very much

**Pull request closed without merging**
